## These two functions work together to return the inverse of a matrix.
## Under R's scoping rules, the first function (makeCacheMatrix - described below) can be
## used to "store" variables and secondary functions, including - most importantly - 
## the inverted matrix. CacheSolve, in turn, calculates the matrix inversion, but
## only after checking to see if the calculation has already been completed and its result
## stored in the makeCacheMatrix function's 'im' variable.



## makeCacheMatrix returns a list of functions that allow the user to get/set
## values. As input, it is passed a matrix ('x').
## These functions are used by the cacheSolve function (see below).
## Note: this function is based on the makeVector function written by Roger Peng
## as part of the course materials for Coursera's 'Introduction to R Programming.'
## source: https://github.com/rdpeng/ProgrammingAssignment2

makeCacheMatrix <- function(x = matrix()) {
	## 'im' stores the inverted matrix
	im <- NULL

	## The 'set' function takes a matrix (as input) and sets it to x.
	## It also resets 'im' to NULL, which informs the CacheSolve function that the
	## matrix inversion needs to be recalculated.
	set <- function(y) {
		x <<- y
		im <<- NULL
		}

	## The 'get' function returns the stored matrix
	get <- function() x

	## The 'setIM' function stores the inverted matrix (after it is passed in by
	## CacheSolve) 
	setIM <- function(newIM) im <<- newIM

	## The 'getIM' function returns the stored inverted matrix (or NULL if absent)
	getIM <- function() im

	## Returns the list of functions defined above (set, get, setIM, getIM)
	funMatrix <- list(set = set, get = get, setIM = setIM, getIM = getIM)
	
}



## cacheSolve returns the inverse of a matrix, either by solving the matrix or
## returning a cached version. It is passed a list of functions ('x') created 
## by the makeCacheMatrix function.
## Note: this function is based on the cachemean function written by Roger Peng
## as part of the course materials for Coursera's 'Introduction to R Programming.'
## source: https://github.com/rdpeng/ProgrammingAssignment2

cacheSolve <- function(x, ...) {
	## First, try to retrieve the inverted matrix from the list of functions
	## generated by makeCacheMatrix (defined above)
	im <- x$getIM()

	## If there is a value in 'im' (apart from NULL), return it.
	if(!is.null(im)) {
		message("getting cached version of inverted matrix")
		return(im)
	}

	## Otherwise, calculate the inverse of the matrix, set the value using
	## the encapsulated function 'setIM' (defined in makeCacheMatrix) and then
	## return the inverted matrix.

	data <- x$get()
	## As per the assignment guidelines, I made the assumption here that this function
	## would only ever receive invertable matrices as input. Otherwise, it would have
	## been necessary to include some error checking code here.
	im <- solve(data, ...)
	x$setIM(im)
	im
}

