## These two functions work together to return the inverse of a matrix.
## There are two distinct usage cases: 1) the matrix has not yet been solved, in
## which case it performs the computation and returns the result; 2) the matrix
## has already been solved, in which case it returns the cached value rather than
## performing the calculation again.


## makeCacheMatrix returns a list of functions that allow the user to get/set
## matrix values. As input, it is passed a matrix ('x').
## These functions are used by the cacheSolve function (see below).
## Note: this function is based on the makeVector function written by Roger Peng
## as part of the course materials for Coursera's 'Introduction to R Programming.'
## source: https://class.coursera.org/rprog-012/human_grading/view/courses/973493/assessments/3/submissions

makeCacheMatrix <- function(x = matrix()) {
	## 'im' stores the inverted matrix
	im <- NULL

	## Overwrites previous values. 
	## Note: resetting 'im' to NULL allows it to be used as a flag, marking whether
	## the 'set' fuction has been employed.
	set <- function(y) {
		x <<- y
		im <<- NULL
		}

	## Returns the stored matrix
	get <- function() x

	## Sets the inverse of the stored matrix
	setIM <- function(newIM) im <<- newIM

	## Returns the stored inverted matrix (or NULL if absent)
	getIM <- function() im

	## Returns list of functions, as defined above.
	funMatrix <- list(set = set, get = get, setIM = setIM, getIM = getIM)
	
}



## cacheSolve returns the inverse of a matrix, either by solving the matrix or
## returning a cached version. It is passed a list of functions ('x') created 
## by the makeCacheMatrix function.
## Note: this function is based on the cachemean function written by Roger Peng
## as part of the course materials for Coursera's 'Introduction to R Programming.'
## source: https://class.coursera.org/rprog-012/human_grading/view/courses/973493/assessments/3/submissions

cacheSolve <- function(x, ...) {
	## Try to retrieve the inverted matrix from the list of functions
	## generated by makeCacheMatrix (defined above)
	im <- x$getIM()

	## If the inverse has already been cached and is unchanged, return it.
	if(!is.null(im)) {
		message("getting cached version of inverted matrix")
		return(im)
	}

	## Otherwise, calculate the inverse of the matrix, set the value into
	## the encapsulated function (defined in makeCacheMatrix) and return it
	data <- x$get()
	im <- solve(data, ...)
	x$setIM(im)
	im
}

